env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures: 
    jsx: true

plugins: ['react']

settings:
  react:
    version: '16'